/*{
  "DESCRIPTION": "Layered luminous wave ribbons inspired by fine-line waveform imagery. Designed for MadMapper audio-reactive parameter mapping.",
  "CREDIT": "Generated by ISF Shader Designer",
  "CATEGORIES": [
    "Generator",
    "Audio Reactive Ready",
    "Lines"
  ],
  "INPUTS": [
    {
      "NAME": "energy",
      "TYPE": "float",
      "DEFAULT": 0.35,
      "MIN": 0.0,
      "MAX": 1.0
    },
    {
      "NAME": "bassDrive",
      "TYPE": "float",
      "DEFAULT": 0.25,
      "MIN": 0.0,
      "MAX": 1.0
    },
    {
      "NAME": "shapeShift",
      "TYPE": "float",
      "DEFAULT": 0.4,
      "MIN": 0.0,
      "MAX": 1.0
    },
    {
      "NAME": "lineSpread",
      "TYPE": "float",
      "DEFAULT": 0.55,
      "MIN": 0.0,
      "MAX": 1.0
    },
    {
      "NAME": "lineCount",
      "TYPE": "float",
      "DEFAULT": 34.0,
      "MIN": 6.0,
      "MAX": 80.0
    },
    {
      "NAME": "mainLineWidth",
      "TYPE": "float",
      "DEFAULT": 0.008,
      "MIN": 0.001,
      "MAX": 0.04
    },
    {
      "NAME": "thinLineWidth",
      "TYPE": "float",
      "DEFAULT": 0.0014,
      "MIN": 0.0004,
      "MAX": 0.008
    },
    {
      "NAME": "amplitude",
      "TYPE": "float",
      "DEFAULT": 0.32,
      "MIN": 0.05,
      "MAX": 0.9
    },
    {
      "NAME": "frequency",
      "TYPE": "float",
      "DEFAULT": 1.15,
      "MIN": 0.25,
      "MAX": 4.0
    },
    {
      "NAME": "flowSpeed",
      "TYPE": "float",
      "DEFAULT": 0.12,
      "MIN": -1.0,
      "MAX": 1.0
    },
    {
      "NAME": "horizontalWarp",
      "TYPE": "float",
      "DEFAULT": 0.22,
      "MIN": 0.0,
      "MAX": 1.0
    },
    {
      "NAME": "twist",
      "TYPE": "float",
      "DEFAULT": 0.55,
      "MIN": -2.0,
      "MAX": 2.0
    },
    {
      "NAME": "glow",
      "TYPE": "float",
      "DEFAULT": 0.65,
      "MIN": 0.0,
      "MAX": 2.0
    },
    {
      "NAME": "brightness",
      "TYPE": "float",
      "DEFAULT": 1.0,
      "MIN": 0.0,
      "MAX": 3.0
    },
    {
      "NAME": "bgColor",
      "TYPE": "color",
      "DEFAULT": [
        0.035,
        0.065,
        0.075,
        1.0
      ]
    },
    {
      "NAME": "lineColor",
      "TYPE": "color",
      "DEFAULT": [
        0.78,
        0.9,
        0.94,
        1.0
      ]
    },
    {
      "NAME": "mainColor",
      "TYPE": "color",
      "DEFAULT": [
        1.0,
        1.0,
        0.96,
        1.0
      ]
    },
    {
      "NAME": "fadeEdges",
      "TYPE": "float",
      "DEFAULT": 0.18,
      "MIN": 0.0,
      "MAX": 0.6
    }
  ]
}*/

#define PI 3.14159265359

float saturate(float x) {
    return clamp(x, 0.0, 1.0);
}

float lineSDF(float y, float curve, float width) {
    float d = abs(y - curve);
    return 1.0 - smoothstep(width, width * 2.6, d);
}

float glowLine(float y, float curve, float width, float amount) {
    float d = abs(y - curve);
    return amount * exp(-d * d / max(width * width, 0.000001));
}

float hash(float n) {
    return fract(sin(n * 41.231) * 43758.5453123);
}

float waveform(vec2 uv, float offset, float phase, float ampMul) {
    float x = uv.x;

    float large = sin((x * frequency + phase) * PI * 1.55);
    float slow  = sin((x * (frequency * 0.55 + 0.15) - phase * 0.34) * PI * 2.0);
    float fine  = sin((x * (frequency * 2.1 + 0.8) + phase * 0.73 + offset * 1.7) * PI * 2.0);

    float rightLift = smoothstep(-0.1, 0.95, x);
    float valley = -0.22 * exp(-pow((x - 0.08) * 1.9, 2.0));
    float rising = 0.38 * rightLift;

    float soundBend = bassDrive * 0.28 * sin((x * 2.8 + TIME * 0.65 + offset) * PI);
    float morph = mix(0.0, shapeShift, 0.85);

    float curve =
        large * 0.34 +
        slow  * 0.22 +
        fine  * 0.035 * morph +
        valley +
        rising +
        soundBend;

    curve *= amplitude * ampMul * (1.0 + energy * 1.15);

    float localWarp = horizontalWarp * 0.11 * sin((x * 3.2 + TIME * 0.21 + offset * 2.0) * PI);
    curve += localWarp;

    return curve;
}

void main() {
    vec2 uv = isf_FragNormCoord.xy;
    vec2 p = uv * 2.0 - 1.0;

    float aspect = RENDERSIZE.x / RENDERSIZE.y;
    p.x *= aspect;

    float t = TIME * flowSpeed;

    vec3 col = bgColor.rgb;

    // subtle vignette / dark background depth
    float vignette = smoothstep(1.45, 0.15, length(vec2(p.x / max(aspect, 0.001), p.y)));
    col *= mix(0.65, 1.08, vignette);

    float edgeFadeX = smoothstep(0.0, fadeEdges, uv.x) * smoothstep(0.0, fadeEdges, 1.0 - uv.x);
    float edgeFadeY = smoothstep(0.0, fadeEdges * 0.55, uv.y) * smoothstep(0.0, fadeEdges * 0.55, 1.0 - uv.y);
    float edgeFade = edgeFadeX * edgeFadeY;

    float nLines = floor(lineCount);
    float thinAccum = 0.0;
    float glowAccum = 0.0;

    for (float i = 0.0; i < 90.0; i++) {
        if (i >= nLines) {
            break;
        }

        float id = i / max(nLines - 1.0, 1.0);
        float centered = id - 0.5;

        float rnd = hash(i + 7.17);
        float phase = t + centered * twist + rnd * 0.23;

        float spread = mix(0.015, 0.19, lineSpread);
        spread *= 1.0 + energy * 0.75;

        float ampMul = 1.0 + centered * 0.32 + sin(id * PI) * bassDrive * 0.45;
        float curve = waveform(p, centered, phase, ampMul);

        // ribbon separation: more separation around the middle, tapering toward crossing points
        float ribbonShape = sin((p.x * 0.72 + 0.46) * PI);
        ribbonShape = sign(ribbonShape) * pow(abs(ribbonShape), 1.15);

        float layerOffset =
            centered * spread * ribbonShape +
            centered * spread * 0.25 * sin((p.x * 2.1 + TIME * 0.18) * PI);

        curve += layerOffset;

        float widthVariation = thinLineWidth * (0.75 + rnd * 0.65);
        float lineMask = lineSDF(p.y, curve, widthVariation);
        float hairGlow = glowLine(p.y, curve, widthVariation * 4.0, 0.035 * glow);

        float depthFade = mix(0.38, 1.0, sin(id * PI));
        float crossingFade = 0.75 + 0.25 * smoothstep(-0.65, 0.95, p.x);

        thinAccum += lineMask * depthFade * crossingFade;
        glowAccum += hairGlow * depthFade;
    }

    // bright primary curve
    float mainCurve = waveform(p, 0.0, t, 1.08);
    mainCurve += 0.015 * sin((p.x * 5.0 + TIME * 0.35) * PI) * shapeShift;

    float mainCore = lineSDF(p.y, mainCurve, mainLineWidth * (1.0 + energy * 0.65));
    float mainHalo = glowLine(p.y, mainCurve, mainLineWidth * 5.0, glow * 0.22);
    float mainSoft = glowLine(p.y, mainCurve, mainLineWidth * 13.0, glow * 0.08);

    vec3 thinRGB = lineColor.rgb * thinAccum * 0.55;
    vec3 glowRGB = lineColor.rgb * glowAccum;
    vec3 mainRGB = mainColor.rgb * (mainCore * 1.65 + mainHalo + mainSoft);

    col += (thinRGB + glowRGB + mainRGB) * edgeFade * brightness;

    // slight cool bloom tint
    col += lineColor.rgb * pow(saturate(thinAccum + mainCore), 2.0) * 0.08 * glow;

    col = pow(max(col, 0.0), vec3(0.92));

    gl_FragColor = vec4(col, 1.0);
}