/*{
  "DESCRIPTION": "Monochrome glowing architectural grid inspired by high contrast black and white structural light patterns.",
  "CREDIT": "Generated by ISF Shader Designer",
  "ISFVSN": "2",
  "CATEGORIES": [
    "Generator",
    "Abstract",
    "Grid",
    "Glitch"
  ],
  "INPUTS": [
    { "NAME": "speed",          "TYPE": "float", "DEFAULT": 0.20, "MIN": 0.0, "MAX": 3.0 },
    { "NAME": "scale",          "TYPE": "float", "DEFAULT": 1.00, "MIN": 0.25, "MAX": 4.0 },
    { "NAME": "gridDensity",    "TYPE": "float", "DEFAULT": 1.00, "MIN": 0.2, "MAX": 4.0 },

    { "NAME": "majorLineWidth", "TYPE": "float", "DEFAULT": 0.018, "MIN": 0.002, "MAX": 0.08 },
    { "NAME": "minorLineWidth", "TYPE": "float", "DEFAULT": 0.006, "MIN": 0.001, "MAX": 0.04 },

    { "NAME": "glow",           "TYPE": "float", "DEFAULT": 1.60, "MIN": 0.0, "MAX": 5.0 },
    { "NAME": "brightness",     "TYPE": "float", "DEFAULT": 1.15, "MIN": 0.0, "MAX": 3.0 },
    { "NAME": "contrast",       "TYPE": "float", "DEFAULT": 1.35, "MIN": 0.2, "MAX": 4.0 },

    { "NAME": "blockAmount",    "TYPE": "float", "DEFAULT": 0.70, "MIN": 0.0, "MAX": 1.0 },
    { "NAME": "subdivision",    "TYPE": "float", "DEFAULT": 0.75, "MIN": 0.0, "MAX": 1.0 },
    { "NAME": "scanlines",      "TYPE": "float", "DEFAULT": 0.35, "MIN": 0.0, "MAX": 1.0 },
    { "NAME": "noiseAmount",    "TYPE": "float", "DEFAULT": 0.12, "MIN": 0.0, "MAX": 1.0 },
    { "NAME": "jitter",         "TYPE": "float", "DEFAULT": 0.18, "MIN": 0.0, "MAX": 1.0 },

    { "NAME": "invert",         "TYPE": "bool", "DEFAULT": false },

    { "NAME": "backgroundColor", "TYPE": "color", "DEFAULT": [0.0, 0.0, 0.0, 1.0] },
    { "NAME": "midColor",        "TYPE": "color", "DEFAULT": [0.34, 0.34, 0.34, 1.0] },
    { "NAME": "lineColor",       "TYPE": "color", "DEFAULT": [1.0, 1.0, 1.0, 1.0] },

    { "NAME": "seed", "TYPE": "float", "DEFAULT": 8.5, "MIN": 0.0, "MAX": 100.0 }
  ]
}*/

#ifdef GL_ES
precision mediump float;
#endif

float sat(float x) {
    return clamp(x, 0.0, 1.0);
}

float hash11(float n) {
    return fract(sin(n) * 43758.5453123);
}

float hash21(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123);
}

float noise(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);

    vec2 u = f * f * (3.0 - 2.0 * f);

    float a = hash21(i);
    float b = hash21(i + vec2(1.0, 0.0));
    float c = hash21(i + vec2(0.0, 1.0));
    float d = hash21(i + vec2(1.0, 1.0));

    return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}

float fbm(vec2 p) {
    float v = 0.0;
    float a = 0.5;

    for (int i = 0; i < 5; i++) {
        v += a * noise(p);
        p = p * 2.03 + vec2(11.17, 19.91);
        a *= 0.5;
    }

    return v;
}

float grid(vec2 uv, vec2 count, float width) {
    vec2 g = fract(uv * count);
    vec2 d = min(g, 1.0 - g);

    float lx = 1.0 - smoothstep(width, width * 2.8, d.x);
    float ly = 1.0 - smoothstep(width, width * 2.8, d.y);

    return max(lx, ly);
}

float rectInside(vec2 uv, vec2 center, vec2 size) {
    vec2 q = abs(uv - center);
    float x = 1.0 - smoothstep(size.x, size.x + 0.002, q.x);
    float y = 1.0 - smoothstep(size.y, size.y + 0.002, q.y);
    return x * y;
}

float rectFrame(vec2 uv, vec2 center, vec2 size, float width) {
    vec2 q = abs(uv - center);
    float outerX = 1.0 - smoothstep(size.x, size.x + 0.004, q.x);
    float outerY = 1.0 - smoothstep(size.y, size.y + 0.004, q.y);

    float innerX = 1.0 - smoothstep(size.x - width, size.x - width + 0.004, q.x);
    float innerY = 1.0 - smoothstep(size.y - width, size.y - width + 0.004, q.y);

    float outer = outerX * outerY;
    float inner = innerX * innerY;

    return sat(outer - inner);
}

float randomLineSet(vec2 uv, float t) {
    float v = 0.0;

    for (int i = 0; i < 28; i++) {
        float fi = float(i);

        float x = hash11(fi * 4.71 + seed);
        float y = hash11(fi * 8.13 + seed + 17.0);

        float wx = minorLineWidth * mix(0.5, 2.6, hash11(fi * 3.17 + seed));
        float wy = minorLineWidth * mix(0.5, 2.2, hash11(fi * 6.41 + seed));

        float vx = 1.0 - smoothstep(wx, wx * 4.0, abs(uv.x - x - 0.004 * sin(t + fi)));
        float hy = 1.0 - smoothstep(wy, wy * 4.0, abs(uv.y - y - 0.004 * cos(t * 0.8 + fi)));

        float activeX = step(0.25, hash11(fi * 9.19 + seed));
        float activeY = step(0.35, hash11(fi * 5.83 + seed));

        v += vx * activeX * 0.45;
        v += hy * activeY * 0.35;
    }

    return sat(v);
}

float blockField(vec2 uv, float t, out float blockTone, out float blockEdges) {
    float value = 0.0;
    blockTone = 0.0;
    blockEdges = 0.0;

    for (int i = 0; i < 18; i++) {
        float fi = float(i);

        vec2 cell = vec2(
            floor(hash11(fi * 2.13 + seed) * 6.0),
            floor(hash11(fi * 5.71 + seed) * 4.0)
        );

        vec2 center = (cell + 0.5) / vec2(6.0, 4.0);

        center += vec2(
            0.012 * sin(t * 0.35 + fi * 1.7),
            0.010 * cos(t * 0.28 + fi * 2.1)
        ) * jitter;

        vec2 size = vec2(
            mix(0.055, 0.18, hash11(fi * 7.31 + seed)),
            mix(0.075, 0.26, hash11(fi * 3.97 + seed))
        );

        float inside = rectInside(uv, center, size);
        float frame = rectFrame(uv, center, size, majorLineWidth * 2.0);

        float toneRandom = hash11(fi * 11.11 + seed);
        float tone = mix(0.03, 0.65, toneRandom);

        float innerTexture =
            fbm((uv - center) * vec2(70.0, 24.0) + fi) * 0.45 +
            fbm((uv - center) * vec2(18.0, 90.0) - fi) * 0.35;

        blockTone += inside * tone * (0.55 + innerTexture);
        blockEdges = max(blockEdges, frame);
        value = max(value, inside * tone);
    }

    blockTone = sat(blockTone * blockAmount);
    blockEdges = sat(blockEdges);

    return sat(value * blockAmount);
}

void main() {
    vec2 uv = isf_FragNormCoord.xy;

    float aspect = RENDERSIZE.x / RENDERSIZE.y;
    vec2 p = uv;
    p.x = (p.x - 0.5) * aspect + 0.5;

    float t = TIME * speed;

    vec2 warp = vec2(
        fbm(p * 3.0 + vec2(t * 0.12, seed)) - 0.5,
        fbm(p * 3.0 + vec2(seed, -t * 0.10)) - 0.5
    );

    p += warp * 0.010 * jitter;

    p = (p - 0.5) / scale + 0.5;

    float blockTone = 0.0;
    float blockEdges = 0.0;
    float blocks = blockField(p, t, blockTone, blockEdges);

    float major =
        grid(p, vec2(5.0, 3.0) * gridDensity, majorLineWidth) * 0.95 +
        grid(p + vec2(0.05, 0.02), vec2(8.0, 5.0) * gridDensity, majorLineWidth * 0.65) * 0.75;

    float minor =
        grid(p + vec2(0.01, 0.03), vec2(22.0, 15.0) * gridDensity, minorLineWidth) * 0.45 +
        grid(p + vec2(0.04, 0.01), vec2(55.0, 38.0) * gridDensity, minorLineWidth * 0.55) * 0.25;

    float randomLines = randomLineSet(p, t) * subdivision;

    float intersections = pow(sat((major + blockEdges) * (minor + randomLines)), 0.55);

    float value = 0.0;

    value += blockTone * 0.65;
    value += blocks * 0.25;
    value += major * 0.95;
    value += minor * subdivision * 0.80;
    value += randomLines * 0.80;
    value += blockEdges * 1.35;
    value += intersections * 1.40;

    // 발광 라인
    float hot = sat(major + blockEdges + intersections);
    value += pow(hot, 1.7) * glow * 0.65;

    // 스캔라인
    float scanY = 0.5 + 0.5 * sin(uv.y * RENDERSIZE.y * 1.25);
    float scanX = 0.5 + 0.5 * sin(uv.x * RENDERSIZE.x * 0.60);

    value *= mix(1.0, 0.72 + scanY * 0.28, scanlines);
    value += scanlines * scanX * 0.035;

    // 필름 노이즈
    float n = hash21(uv * RENDERSIZE.xy + TIME * 31.7);
    value += (n - 0.5) * noiseAmount * 0.20;

    // 명암 조정
    value *= brightness;
    value = pow(sat(value), 1.0 / max(contrast, 0.001));

    // 발광 느낌의 소프트 클리핑
    value = 1.0 - exp(-value * 1.6);
    value = sat(value);

    vec3 bg = backgroundColor.rgb;
    vec3 mid = midColor.rgb;
    vec3 white = lineColor.rgb;

    vec3 col = mix(bg, mid, sat(blockTone + blocks * 0.4));
    col = mix(col, white, value);

    if (invert) {
        col = 1.0 - col;
    }

    gl_FragColor = vec4(clamp(col, 0.0, 1.0), 1.0);
}