/*{
    "DESCRIPTION": "Subtle premium abstract background for classical and electronic music performances. Slow flowing gradients with restrained projection-friendly colors.",
    "CREDIT": "Generated by ISF Shader Designer",
    "CATEGORIES": [
        "Generator",
        "Abstract",
        "Performance"
    ],
    "INPUTS": [
        {
            "NAME": "intensity",
            "TYPE": "float",
            "DEFAULT": 0.45,
            "MIN": 0.0,
            "MAX": 1.0,
            "LABEL": "Overall Intensity"
        },
        {
            "NAME": "motionSpeed",
            "TYPE": "float",
            "DEFAULT": 0.18,
            "MIN": 0.0,
            "MAX": 1.0,
            "LABEL": "Motion Speed"
        },
        {
            "NAME": "scale",
            "TYPE": "float",
            "DEFAULT": 1.15,
            "MIN": 0.5,
            "MAX": 3.0,
            "LABEL": "Spatial Scale"
        },
        {
            "NAME": "softness",
            "TYPE": "float",
            "DEFAULT": 0.65,
            "MIN": 0.0,
            "MAX": 1.0,
            "LABEL": "Softness"
        },
        {
            "NAME": "contrast",
            "TYPE": "float",
            "DEFAULT": 0.28,
            "MIN": 0.0,
            "MAX": 1.0,
            "LABEL": "Contrast"
        },
        {
            "NAME": "grainAmount",
            "TYPE": "float",
            "DEFAULT": 0.025,
            "MIN": 0.0,
            "MAX": 0.12,
            "LABEL": "Fine Grain"
        },
        {
            "NAME": "palette",
            "TYPE": "long",
            "VALUES": [
                0,
                1,
                2,
                3
            ],
            "LABELS": [
                "Warm Ivory / Bronze",
                "Cool Blue / Slate",
                "Muted Violet / Charcoal",
                "Monochrome Silver"
            ],
            "DEFAULT": 0,
            "LABEL": "Color Palette"
        },
        {
            "NAME": "vignette",
            "TYPE": "float",
            "DEFAULT": 0.38,
            "MIN": 0.0,
            "MAX": 1.0,
            "LABEL": "Vignette"
        }
    ]
}*/

float hash(vec2 p) {
    p = fract(p * vec2(123.34, 456.21));
    p += dot(p, p + 45.32);
    return fract(p.x * p.y);
}

float noise(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);

    f = f * f * (3.0 - 2.0 * f);

    float a = hash(i);
    float b = hash(i + vec2(1.0, 0.0));
    float c = hash(i + vec2(0.0, 1.0));
    float d = hash(i + vec2(1.0, 1.0));

    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}

float fbm(vec2 p) {
    float v = 0.0;
    float amp = 0.5;

    for (int i = 0; i < 5; i++) {
        v += amp * noise(p);
        p = mat2(1.62, -1.18, 1.18, 1.62) * p;
        amp *= 0.5;
    }

    return v;
}

vec3 getPalette(float t) {
    vec3 a;
    vec3 b;
    vec3 c;

    if (palette == 0) {
        // Warm ivory, muted bronze, deep umber
        a = vec3(0.075, 0.065, 0.055);
        b = vec3(0.62, 0.52, 0.39);
        c = vec3(0.92, 0.84, 0.68);
    } else if (palette == 1) {
        // Cool slate, desaturated blue, soft moonlight
        a = vec3(0.045, 0.055, 0.070);
        b = vec3(0.32, 0.39, 0.48);
        c = vec3(0.72, 0.78, 0.84);
    } else if (palette == 2) {
        // Charcoal, muted violet, pale lavender-gray
        a = vec3(0.050, 0.045, 0.060);
        b = vec3(0.34, 0.28, 0.42);
        c = vec3(0.72, 0.66, 0.78);
    } else {
        // Monochrome silver
        a = vec3(0.045);
        b = vec3(0.42);
        c = vec3(0.78);
    }

    float m = smoothstep(0.08, 0.95, t);
    vec3 col = mix(a, b, m);
    col = mix(col, c, smoothstep(0.68, 1.0, t) * 0.45);

    return col;
}

void main() {
    vec2 uv = gl_FragCoord.xy / RENDERSIZE.xy;
    vec2 aspect = vec2(RENDERSIZE.x / RENDERSIZE.y, 1.0);

    vec2 p = (uv - 0.5) * aspect;
    float t = TIME * motionSpeed;

    // Very slow drifting coordinate field
    vec2 drift = vec2(
        sin(t * 0.37) * 0.18,
        cos(t * 0.29) * 0.14
    );

    vec2 q = p * scale + drift;

    // Layered soft turbulence
    float n1 = fbm(q * 1.05 + vec2(t * 0.07, -t * 0.04));
    float n2 = fbm(q * 1.85 - vec2(t * 0.045, t * 0.06));
    float n3 = fbm(q * 3.20 + vec2(sin(t * 0.2), cos(t * 0.17)) * 0.25);

    float field = n1 * 0.56 + n2 * 0.31 + n3 * 0.13;

    // Slow diagonal luminous structure, softened for projection
    float diagonal = dot(p, normalize(vec2(0.85, 0.42)));
    float wave = sin(diagonal * 5.2 + field * 3.4 + t * 0.55);
    wave = wave * 0.5 + 0.5;

    float form = mix(field, wave, 0.28);
    form = smoothstep(0.18 + softness * 0.18, 0.92, form);

    // Projection-safe restrained contrast
    form = mix(0.42, form, 0.55 + contrast * 0.45);

    vec3 color = getPalette(form);

    // Subtle center glow, not overly bright
    float r = length(p);
    float glow = exp(-r * 2.15) * 0.28;
    color += glow * getPalette(0.78) * intensity;

    // Gentle vignette keeps edges controlled on large projection surfaces
    float vig = smoothstep(0.95, 0.18, r);
    color *= mix(1.0 - vignette * 0.72, 1.0, vig);

    // Fine film-like grain to reduce banding in gradients
    float grain = hash(gl_FragCoord.xy + fract(TIME) * 137.0) - 0.5;
    color += grain * grainAmount;

    // Final intensity control, kept within modest luminance range
    color *= mix(0.55, 1.05, intensity);

    // Soft desaturation for a more refined stage look
    float luma = dot(color, vec3(0.299, 0.587, 0.114));
    color = mix(vec3(luma), color, 0.72);

    // Avoid harsh whites and crushed blacks
    color = clamp(color, 0.015, 0.92);

    gl_FragColor = vec4(color, 1.0);
}